<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer|Laminas\Mvc\Plugin\FlashMessenger\View\HelperTrait $this
 */

use UserModule\Form\LoginForm;

$loginForm = $this->loginForm;
$loginForm->setAttribute("action", $this->actionUrl);
$loginForm->prepare();
if ($this->flashMessenger()->hasMessages()) {
    echo $this->flashMessenger()->render("error", ["alert", "alert-dismissible", "alert-danger",]);
}
$this->flashMessenger()
    ->clearMessages();
?>
<div class="row align-items-center justify-content-center">
    <div class="col-md-6 shadow-sm">
        <h2 class="pt-2 text-center">
            <span class="text-muted"><?php echo $this->title ?></span>
        </h2>
        <?php echo $this->form()->openTag($loginForm); ?>
        <div class="mb-3">
            Email
            <div class="input-group">
                <?php echo $this->authEmail ?>
            </div>
        </div>

        <div class="mb-3">
            <?php echo $this->formLabel($loginForm->get(LoginForm::TEXT_PASSWORD)); ?>
            <div class="input-group">
                <?php echo $this->formPassword($loginForm->get(LoginForm::TEXT_PASSWORD)); ?>
            </div>
            <div class="text-danger">
                <?php echo $this->formElementErrors($loginForm->get(LoginForm::TEXT_PASSWORD)); ?>
            </div>
        </div>

        <div class="mb-3">
            <div class="mb-3">
                <?php echo $this->formSubmit($loginForm->get(LoginForm::TEXT_SUBMIT)); ?>
            </div>
        </div>
        <div class="mb-3">
            <div class="mb-3">
                <a href="<?php echo $this->url("user/actions", ["controller" => "UserController", "action" => "logout"]) ?>">Cancel</a>
            </div>
        </div>
        <?php echo $this->form()
            ->closeTag(); ?>
    </div>
</div>
